apiVersion: v1
kind: Service
metadata: 
    name: clusteripstud
    labels:
      app: clusteripstud
spec: 
    selector:
      app: studentapp-pod
    type: ClusterIP
    ports:
      - port: 8080
        targetPort: 8080