apiVersion: v1
kind: Pod
metadata:
  name: counter-pod
  labels: 
    app: counter-pod
spec: 
    containers:
      - name: conunter-cont
        image: learnerkaran/counter:latest
        ports:
          - containerPort: 80
            name: http
            protocol: TCP