apiVersion: v1
kind: Service
metadata:
    name: loadbalancercounter
    namespace: namecounterdevenv
    labels: 
      app: loadbalancercounter
spec:
  selector:
    app: counter-pod
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80