apiVersion: v1
kind: Service
metadata: 
  name: clusteripcounter
  labels: 
     app: clusteripcounter
spec:
  selector: 
    app: counter-pod
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80