apiVersion: v1
kind: Service
metadata: 
    name: lbstudapp
    labels:
      app: lbstudapp
spec:
    selector: 
      app: studentapp-pod
    type: LoadBalancer
    ports: 
      - port: 8080
        targetPort: 8080
