apiVersion: v1
kind: Service
metadata: 
    name: nodeportcounter
    labels: 
      app: nodeportcounter
spec:
    selector:
      app: counter-pod
    type: NodePort
    ports:
      - port: 80
        targetPort: 80