apiVersion: v1
kind: Service
metadata: 
    name: nodeportemployee
    labels: 
      app: nodeportemployee
spec: 
    selector: 
        app: employeeapp-pod
    type: NodePort
    ports:
      - port: 3000
        targetPort: 3000